// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'signup': string;
  'signup__closeBtn': string;
  'signup__formWrapper': string;
  'signup__success': string;
}
export const cssExports: CssExports;
export default cssExports;
