// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'signin': string;
  'signin__closeBtn': string;
  'signin__formWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
