// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'weather': string;
  'weather__loader': string;
  'weather__options': string;
  'weather__selectWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
