// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth': string;
  'auth__avatar': string;
  'auth__hint': string;
}
export const cssExports: CssExports;
export default cssExports;
